apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-k8s-back
  labels:
    app: mongo-k8s
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: mongo-k8s
        component: back
    spec:
      containers:
        - name: mongo-k8s-back
          image: techcloudifyme/mongodb-back
          ports: 
            - containerPort: 3000
          env: 
            - name: PORT
              value: "3000"
            - name: CONN_STR
              value: "$ATLAS_CONNECTION_STRING"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-k8s-back
  labels:
    app: mongo-k8s
    component: back
spec:
  type: LoadBalancer
  selector:
    component: back
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-k8s-front
  labels:
    app: mongo-k8s
    component: front
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: front
  template:
    metadata: 
      labels:
        app: mongo-k8s
        component: front
    spec:
      containers:
        - name: mongo-k8s-front
          image: techcloudifyme/mongodb-front
          ports: 
            - containerPort: 80
          env: 
            - name: BASE_URL
              value: "http://54.88.141.224:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-k8s-front
  labels:
    app: mongo-k8s
    component: front
spec:
  type: LoadBalancer
  selector:
    component: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
