apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: atlas-user
spec:
  roles:
    - roleName: "readWriteAnyDatabase"
      databaseName: "mydb"
  projectRef:
    name: mongo-k8s-project
  username: k8user
  passwordSecretRef:
    name: atlaspassword

